name: Tests

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php-versions: [ '8.0', '8.1', '8.2' ]
        phpunit-version: [ '9.5' ]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ matrix.phpunit-version }}, composer:v2
          extensions: curl, dom, exif, gd, hash, json, libxml, zip, zlip, mbstring, pdo, bcmath, gmp
          coverage: xdebug

      - name: Validate Composer json/lock
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-progress

      - name: Run Unit Tests
        run: _protected/vendor/bin/phpunit --testsuite "pH7Builder Protected CI"
